name: OnDemand‑21‑Categories

on:
  # === 00:00 LOCAL (edit to your UTC offset) =================
  # Eastern (UTC‑4)   → 04:00 UTC
  # Central (UTC‑5)   → 05:00 UTC
  # Mountain (UTC‑6)  → 06:00 UTC
  # Pacific (UTC‑7)   → 07:00 UTC
  schedule:
    - cron: '0 4 * * *'          # <‑‑ midnight Eastern
  workflow_dispatch:

jobs:
  run_all:
    runs-on: ubuntu-latest
    steps:
      - name: Clear sheet at midnight
        run: |
          curl -sSL "${{ secrets.OND_WEBAPP }}?secret=${{ secrets.OND_SECRET }}&task=clear"

      - name: Loop through 21 categories every 20 min
        run: |
          declare -a cats=(
            "Automotive%20Care" "Baby" "Bath%20%26%20Body" "Hair%20Care" "Makeup"
            "Skin%20Care" "Electronics" "Toys%20%26%20Games"
            "Tools%20%26%20Home%20Improvement" "Sports%20%26%20Outdoors"
            "Dog%20Supplies" "Cat%20Supplies" "Patio%2C%20Lawn%20%26%20Garden"
            "Office%20Products" "Grocery" "Health%20%26%20Personal%20Care"
            "Bath" "Kitchen%20%26%20Dining" "Storage%20%26%20Organization"
            "Men%20Fashion" "Women%20Fashion"
          )
          for i in "${!cats[@]}"; do
            cat="${cats[$i]}"
            echo "[$(date '+%F %T')] calling $cat"
            curl -sSL "${{ secrets.OND_WEBAPP }}?secret=${{ secrets.OND_SECRET }}&task=$cat"
            [[ $i -lt 20 ]] && sleep $((20*60))
          done
