name: Grocery‑Daily‑22h30

on:
  # ────────────────  22:30 local  ────────────────
  # Local 22:30  (UTC‑4)  ➜  02:30 UTC  next day
  schedule:
    - cron: '30 2 * * *'         # 02:30 UTC = 22:30 EDT / 21:30 EST
  workflow_dispatch:             # manual “Run workflow” button

jobs:
  call_script:
    runs-on: ubuntu-latest
    steps:
      - name: Call Apps‑Script Web‑App
        run: |
          curl -sSL "${{ secrets.OND_WEBAPP }}?secret=${{ secrets.OND_SECRET }}&task=grocery"
