name: OnDemand‑21‑Categories

on:
  schedule:
    # 04:00 UTC  = 00:00 EDT  / 23:00 EST  / 21:00 PDT
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  run_all:
    runs-on: ubuntu-latest
    steps:
      # ---------- midnight wipe ----------
      - name: Clear sheet at midnight
        run: |
          curl -sSL "${{ secrets.OND_WEBAPP }}?secret=${{ secrets.OND_SECRET }}&task=clear"

      # ---------- 21 categories ----------
      - name: Loop through categories every 20 min
        run: |
          declare -a cats=(
            "Automotive%20Care" "Baby" "Bath%20%26%20Body" "Hair%20Care" "Makeup"
            "Skin%20Care" "Electronics" "Toys%20%26%20Games"
            "Tools%20%26%20Home%20Improvement" "Sports%20%26%20Outdoors"
            "Dog%20Supplies" "Cat%20Supplies" "Patio%2C%20Lawn%20%26%20Garden"
            "Office%20Products" "Grocery" "Health%20%26%20Personal%20Care"
            "Bath" "Kitchen%20%26%20Dining" "Storage%20%26%20Organization"
            "Men%20Fashion" "Women%20Fashion"
          )
          for i in "${!cats[@]}"; do
            cat="${cats[$i]}"
            echo "[$(date '+%F %T')] calling $cat"
            curl -sSL "${{ secrets.OND_WEBAPP }}?secret=${{ secrets.OND_SECRET }}&task=$cat"
            # pause 20 min except after last call
            [[ $i -lt 20 ]] && sleep $((20*60))
          done
